apiVersion: v1
kind: {{ .Values.database.volume.pv.kind }}
metadata:
  name: {{ .Values.database.volume.pv.name }}
spec:
  storageClassName: {{ .Values.database.volume.pv.storageClassName}}
  capacity:
    storage: {{ .Values.database.volume.pv.storage }}
  accessModes:
    - {{ .Values.database.volume.pv.accessMode }}
  hostPath:
    path: {{ .Values.database.volume.pv.path }}