apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  type: {{ .Values.database.service.type }}
  selector:
    app: {{ .Values.database.name}}
  ports:
    - port: {{ .Values.database.service.port}}
      targetPort: {{ .Values.database.container.port }}
