apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Values.backend.name}}
  ports:
    - port: {{ .Values.backend.service.port}}
      targetPort: {{ .Values.backend.container.port }}
