apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.frontend.service.ports.port }}
      targetPort: {{ .Values.frontend.service.ports.targetPort }}
      nodePort: {{ .Values.frontend.service.ports.nodePort }}